version: "3"

services: 
    api:
        build: .
        container_name: customermanagement
        ports: 
            - "8080:8080"
        networks: 
            - frontend
            - backend
        environment: 
            - "USER_DATABASE=mysql"
            - "PASSWORD_DATABASE=123456"
        restart: always

    db: 
        image: mysql
        container_name: mysql-customermanagement
        networks: 
            - backend
        environment:            
            - "MYSQL_ROOT_PASSWORD=102030"
            - "MYSQL_USER=mysql"
            - "MYSQL_PASSWORD=123456"
            - "MYSQL_DATABASE=integracao_jira"
        volumes: 
            - C:/docker/volume/customermanagement/mysql:/var/lib/mysql
        ports: 
            - "3306:3306"
        restart: always

networks: 
    frontend:
        driver: bridge
    backend:
        driver: bridge